// Generated by CoffeeScript 1.7.1
(function() {
  var addDimension, addMetric, buildRegex, checkDimension, checkFilter, checkMetric, checkSegment, checkSort, dimensions, dimensions_regex, getDimension, getMetric, metrics, metrics_regex;

  dimensions = [];

  metrics = [];

  metrics_regex = null;

  dimensions_regex = null;

  addMetric = function(met, name, regex) {
    if (regex == null) {
      regex = met;
    }
    return metrics.push({
      value: met,
      name: name,
      regex: new RegExp("^" + regex + "$")
    });
  };

  addDimension = function(dim, name, regex) {
    if (regex == null) {
      regex = dim;
    }
    return dimensions.push({
      value: dim,
      name: name,
      regex: new RegExp("^" + regex + "$")
    });
  };

  getDimension = function(dim) {
    var dimension, _i, _len;
    for (_i = 0, _len = dimensions.length; _i < _len; _i++) {
      dimension = dimensions[_i];
      if (dimension.regex.test(dim)) {
        return dimension;
      }
    }
    return null;
  };

  getMetric = function(met) {
    var metric, _i, _len;
    for (_i = 0, _len = metrics.length; _i < _len; _i++) {
      metric = metrics[_i];
      if (metric.regex.test(met)) {
        return metric;
      }
    }
    return null;
  };

  checkDimension = function(dim) {
    return dimensions_regex.test(dim);
  };

  checkMetric = function(met) {
    return metrics_regex.test(met);
  };

  checkSort = function(sort) {
    var check;
    if (sort.length === 0) {
      return false;
    }
    check = sort[0] === '-' ? sort.replace(/^-/, '') : sort;
    return checkMetric(check) || checkDimension(check);
  };

  checkSegment = function(seg) {
    var is_dynamic;
    is_dynamic = new RegExp('^dynamic::').test(seg);
    if (is_dynamic) {
      return checkFilter(seg.replace(/^dynamic::/, ''));
    } else {
      return new RegExp('^gaid::-?[0-9]+$').test(seg);
    }
  };

  checkFilter = function(filter) {
    var and_exp, and_exps, components, exp_type, ga_name, or_exp, or_exps, _i, _j, _len, _len1;
    and_exps = filter.split(';');
    for (_i = 0, _len = and_exps.length; _i < _len; _i++) {
      and_exp = and_exps[_i];
      or_exps = and_exp.split(',');
      exp_type = null;
      for (_j = 0, _len1 = or_exps.length; _j < _len1; _j++) {
        or_exp = or_exps[_j];
        if (exp_type == null) {
          ga_name = or_exp.split(new RegExp('==|!=|=@|!@|=~|!~|!=|>|<|>=|<=', 'g'), 2)[0];
          if (checkMetric(ga_name)) {
            exp_type = 'metric';
          } else if (checkDimension(ga_name)) {
            exp_type = 'dimension';
          } else {
            return false;
          }
        }
        components = exp_type === 'metric' ? components = or_exp.split(new RegExp('==|!=|>|<|>=|<=', 'g'), 2) : or_exp.split(new RegExp('==|!=|=@|!@|=~|!~', 'g'), 2);
        if (exp_type === 'metric') {
          if (!checkMetric(components[0]) || !/^[0-9]+$/.test(components[1])) {
            return false;
          }
        } else {
          if (!checkDimension(components[0])) {
            return false;
          }
        }
      }
    }
    return true;
  };

  buildRegex = function() {
    var dim, dreg, i, metric, mreg, _i, _j, _len, _len1;
    mreg = '';
    for (i = _i = 0, _len = metrics.length; _i < _len; i = ++_i) {
      metric = metrics[i];
      if (i !== 0) {
        mreg += '|';
      }
      mreg += metric.regex.source;
    }
    metrics_regex = new RegExp(mreg);
    dreg = '';
    for (i = _j = 0, _len1 = dimensions.length; _j < _len1; i = ++_j) {
      dim = dimensions[i];
      if (i !== 0) {
        dreg += '|';
      }
      dreg += dim.regex.source;
    }
    return dimensions_regex = new RegExp(dreg);
  };

  addMetric('ga:visitors', 'Visitors');

  addMetric('ga:newVisits', 'New Visits');

  addMetric('ga:percentNewVisits', 'Percent New Visits');

  addDimension('ga:visitorType', 'Visitor Type');

  addDimension('ga:visitCount', 'Visit Count');

  addDimension('ga:daysSinceLastVisit', 'Days Since Last Visit');

  addDimension('ga:userDefinedValue', 'User Defined Value');

  addMetric('ga:visits', 'Visits');

  addMetric('ga:bounces', 'Bounces');

  addMetric('ga:entranceBounceRate', 'Entrance Bounce Rate');

  addMetric('ga:visitBounceRate', 'Visit Bounce Rate');

  addMetric('ga:timeOnSite', 'Time On Site');

  addMetric('ga:avgTimeOnSite', 'Average Time On Site');

  addDimension('ga:visitLength', 'Visit Length');

  addMetric('ga:organicSearches', 'Organic Searches');

  addDimension('ga:referralPath', 'Referral Path');

  addDimension('ga:campaign', 'Campaign');

  addDimension('ga:source', 'Source');

  addDimension('ga:medium', 'Medium');

  addDimension('ga:keyword', 'Keyword');

  addDimension('ga:adContent', 'Ad Content');

  addDimension('ga:socialNetwork', 'Social Network');

  addDimension('ga:hasSocialSourceReferral', 'Has Social Source Referral');

  addDimension('ga:fullReferrer', 'Full Referrer');

  addDimension('ga:sourceMedium', 'Source Medium');

  addMetric('ga:impressions', 'Impressions');

  addMetric('ga:adClicks', 'Ad Clicks');

  addMetric('ga:adCost', 'Ad Cost');

  addMetric('ga:CPM', 'Cost Per Thousand Impressions');

  addMetric('ga:CPC', 'Cost to Advertiser Per Click');

  addMetric('ga:CTR', 'Click Through Rate');

  addMetric('ga:costPerTransaction', 'Cost Per Transaction');

  addMetric('ga:costPerGoalConversion', 'Cost Per Goal Conversion');

  addMetric('ga:RPC', 'Revenue Per Click');

  addMetric('ga:ROI', 'Returns On Investment');

  addMetric('ga:margin', 'Margin');

  addDimension('ga:adGroup', 'Ad Group');

  addDimension('ga:adSlot', 'Ad Slot');

  addDimension('ga:adSlotPosition', 'Ad Slot Position');

  addDimension('ga:adDistributionNetwork', 'Ad Distribution Network');

  addDimension('ga:adMatchType', 'Ad Match Type');

  addDimension('ga:adMatchedQuery', 'Ad Matched Query');

  addDimension('ga:adPlacementDomain', 'Ad Placement Domain');

  addDimension('ga:adPlacementUrl', 'Ad Placement Url');

  addDimension('ga:adFormat', 'Ad Format');

  addDimension('ga:adTargetingType', 'Ad Targeting Type');

  addDimension('ga:adTargetingOption', 'Ad Targeting Option');

  addDimension('ga:adDisplayUrl', 'Ad Display Url');

  addDimension('ga:adDestinationUrl', 'Ad Destination Url');

  addDimension('ga:adwordsCustomerID', 'Adwords Customer ID');

  addDimension('ga:adwordsCampaignID', 'Adwords Campaign ID');

  addDimension('ga:adwordsAdGroupID', 'Adwords Ad Group ID');

  addDimension('ga:adwordsCreativeID', 'Adwords Creative ID');

  addDimension('ga:adwordsCriteriaID', 'Adwords Criteria ID');

  addMetric('ga:adsenseRevenue', 'AdSense Revenue');

  addMetric('ga:adsenseAdUnitsViewed', 'AdSense Ad Units Viewed');

  addMetric('ga:adsenseAdsViewed', 'AdSense Ads Viewed');

  addMetric('ga:adsenseAdsClicks', 'AdSense Ads Clicks');

  addMetric('ga:adsensePageImpressions', 'AdSense Page Impressions');

  addMetric('ga:adsenseCTR', 'AdSenseCTR');

  addMetric('ga:adsenseECPM', 'AdSenseECPM');

  addMetric('ga:adsenseExits', 'AdSenseExits');

  addMetric('ga:goal(n)Start', 'Goal Start', 'ga:goal([0-9]+)Start');

  addMetric('ga:goalStartsAll', 'All Goal Starts');

  addMetric('ga:goal(n)Completions', 'Goal Completions', 'ga:goal([0-9]+)Completions');

  addMetric('ga:goalCompletionsAll', 'All Goal Completions');

  addMetric('ga:goal(n)Value', 'Goal Value', 'ga:goal([0-9]+)Value');

  addMetric('ga:goalValueAll', 'All Goal Values');

  addMetric('ga:goalValuePerVisit', 'Goal Value Per Visit');

  addMetric('ga:goal(n)ConversionRate', 'Goal Conversion Rate', 'ga:goal([0-9]+)ConversionRate');

  addMetric('ga:goalConversionRateAll', 'All Goal Conversion Rates');

  addMetric('ga:goal(n)Abandons', 'Goal Abandons', 'ga:goal([0-9]+)Abandons');

  addMetric('ga:goalAbandonsAll', 'All Goal Abandons');

  addMetric('ga:goal(n)AbandonRate', 'Goal Abandon Rate', 'ga:goal([0-9]+)AbandonRate');

  addMetric('ga:goalAbandonRateAll', 'All Goals Abandon Rate');

  addDimension('ga:browser', 'Browser');

  addDimension('ga:browserVersion', 'Browser Version');

  addDimension('ga:operatingSystem', 'Operating System');

  addDimension('ga:operatingSystemVersion', 'Operating System Version');

  addDimension('ga:deviceCategory', 'Device Category');

  addDimension('ga:isMobile', 'Is Mobile');

  addDimension('ga:isTablet', 'Is Tablet');

  addDimension('ga:mobileDeviceMarketingName', 'Mobile Device Marketing Name');

  addDimension('ga:mobileDeviceBranding', 'Mobile Device Branding');

  addDimension('ga:mobileDeviceModel', 'Mobile Device Model');

  addDimension('ga:mobileInputSelector', 'Mobile Input Selector');

  addDimension('ga:mobileDeviceInfo', 'Mobile Device Info');

  addDimension('ga:continent', 'Continent');

  addDimension('ga:subContinent', 'Sub Continent');

  addDimension('ga:country', 'Country');

  addDimension('ga:region', 'Region');

  addDimension('ga:metro', 'Metro');

  addDimension('ga:city', 'City');

  addDimension('ga:latitude', 'Latitude');

  addDimension('ga:longitude', 'Longitude');

  addDimension('ga:networkDomain', 'Network Domain');

  addDimension('ga:networkLocation', 'Network Location');

  addDimension('ga:flashVersion', 'Flash Version');

  addDimension('ga:javaEnabled', 'Java Enabled');

  addDimension('ga:language', 'Language');

  addDimension('ga:screenColors', 'Screen Colors');

  addDimension('ga:screenResolution', 'Screen Resolution');

  addMetric('ga:socialActivities', 'Social Activities');

  addDimension('ga:socialActivityEndorsingUrl', 'Social Activity Endorsing Url');

  addDimension('ga:socialActivityDisplayName', 'Social Activity Display Name');

  addDimension('ga:socialActivityPost', 'Social Activity Post');

  addDimension('ga:socialActivityTimestamp', 'Social Activity Timestamp');

  addDimension('ga:socialActivityUserHandle', 'Social Activity User Handle');

  addDimension('ga:socialActivityUserPhotoUrl', 'Social Activity User Photo Url');

  addDimension('ga:socialActivityUserProfileUrl', 'Social Activity User Profile Url');

  addDimension('ga:socialActivityContentUrl', 'Social Activity Content Url');

  addDimension('ga:socialActivityTagsSummary', 'Social Activity Tags Summary');

  addDimension('ga:socialActivityAction', 'Social Activity Action');

  addDimension('ga:socialActivityNetworkAction', 'Social Activity Network Action');

  addMetric('ga:entrances', 'Entrances');

  addMetric('ga:entraceRate', 'Entrance Rate');

  addMetric('ga:pageviews', 'Page Views');

  addMetric('ga:pageviewsPerVisit', 'Page Views Per Visit');

  addMetric('ga:uniquePageviews', 'Unique Page Views');

  addMetric('ga:timeOnPage', 'Time On Page');

  addMetric('ga:avgTimeOnPage', 'Average Time On Page');

  addMetric('ga:exits', 'Exits');

  addMetric('ga:exitRate', 'Exit Rate');

  addDimension('ga:hostname', 'Hostname');

  addDimension('ga:pagePath', 'Page Path');

  addDimension('ga:pagePathLevel1', 'Page Path Level 1');

  addDimension('ga:pagePathLevel2', 'Page Path Level 2');

  addDimension('ga:pagePathLevel3', 'Page Path Level 3');

  addDimension('ga:pagePathLevel4', 'Page Path Level 4');

  addDimension('ga:pageTitle', 'Page Title');

  addDimension('ga:landingPagePath', 'Landing Page Path');

  addDimension('ga:secondPagePath', 'Second Page Path');

  addDimension('ga:exitPagePath', 'Exit Page Path');

  addDimension('ga:previousPagePath', 'Previous Page Path');

  addDimension('ga:nextPagePath', 'Next Page Path');

  addDimension('ga:pageDepth', 'Page Depth');

  addMetric('ga:searchResultViews', 'Search Result Views');

  addMetric('ga:searchUniques', 'Unique Searches');

  addMetric('ga:avgSearchResultViews', 'Average Search Result Views');

  addMetric('ga:searchVisits', 'Search Visits');

  addMetric('ga:percentVisitsWithSearch', 'Percent Visits with Search');

  addMetric('ga:searchDepth', 'Search Depth');

  addMetric('ga:searchRefinements', 'Search Refinements');

  addMetric('ga:searchDuration', 'Search Duration');

  addMetric('ga:avgSearchDuration', 'Average Search Duration');

  addMetric('ga:searchExits', 'Search Exits');

  addMetric('ga:searchExitRate', 'Search Exit Rate');

  addMetric('ga:searchGoal(n)ConversionRate', 'Search Goal Conversion Rate', 'ga:searchGoal([0-9]+)ConversionRate');

  addMetric('ga:searchGoalConversionRateAll', 'Search All Goals Conversion Rate');

  addMetric('ga:goalValueAllPerSearch', 'Goal Value Per Search');

  addDimension('ga:searchUsed', 'Search Used');

  addDimension('ga:searchKeyword', 'Search Keyword');

  addDimension('ga:searchKeywordRefinement', 'Search Keyword Refinement');

  addDimension('ga:searchCategory', 'Search Category');

  addDimension('ga:searchStartPage', 'Search Start Page');

  addDimension('ga:searchDestinationPage', 'Search Destination Page');

  addMetric('ga:pageLoadTime', 'Page Load Time');

  addMetric('ga:pageLoadSample', 'Page Load Sample');

  addMetric('ga:avgPageLoadTime', 'Average Page Load Time');

  addMetric('ga:domainLookupTime', 'Domain Lookup Time');

  addMetric('ga:avgDomainLookupTime', 'Average Domain Lookup Time');

  addMetric('ga:pageDownloadTime', 'Page Download Time');

  addMetric('ga:avgPageDownloadTime', 'Average Page Download Time');

  addMetric('ga:redirectionTime', 'Redirection Time');

  addMetric('ga:avgRedirectionTime', 'Average Redirection Time');

  addMetric('ga:serverConnectionTime', 'Server Connection Time');

  addMetric('ga:avgServerConnectionTime', 'Average Server Connection Time');

  addMetric('ga:serverResponseTime', 'Server Response Time');

  addMetric('ga:avgServerResponseTime', 'Average Server Response Time');

  addMetric('ga:speedMetricsSample', 'Speed Metrics Sample');

  addMetric('ga:domInteractiveTime', 'DOM Interactive Time');

  addMetric('ga:avgDomInteractiveTime', 'Average DOM Interactive Time');

  addMetric('ga:domContentLoadedTime', 'DOM Content Loaded Time');

  addMetric('ga:avgDomContentLoadedTime', 'Average DOM Content Loaded Time');

  addMetric('ga:domLatencyMetricsSample', 'DOM Latency Merics Sample');

  addMetric('ga:appviews', 'App Views');

  addMetric('ga:uniqueAppviews', 'Unique App Views');

  addMetric('ga:appviewsPerVisit', 'App Views Per Visit');

  addMetric('ga:screenviews', 'Screenviews');

  addMetric('ga:uniqueScreenviews', 'Unique Screenviews');

  addMetric('ga:screenviewsPerSession', 'Screenviews Per Session');

  addMetric('ga:timeOnScreen', 'Time On Screen');

  addMetric('ga:avgScreenviewDuration', 'Average Screenview Duration');

  addDimension('ga:appInstallerId', 'App Installer Id');

  addDimension('ga:appVersion', 'App Version');

  addDimension('ga:appName', 'App Name');

  addDimension('ga:appId', 'App Id');

  addDimension('ga:screenName', 'Screen Name');

  addDimension('ga:screenDepth', 'Screen Depth');

  addDimension('ga:landingScreenName', 'Landing Screen Name');

  addDimension('ga:exitScreenName', 'Exit Screen Name');

  addMetric('ga:totalEvents', 'Total Events');

  addMetric('ga:uniqueEvents', 'Unique Events');

  addMetric('ga:eventValue', 'Event Value');

  addMetric('ga:avgEventValue', 'Average Event Value');

  addMetric('ga:visitsWithEvent', 'Visits With Event');

  addMetric('ga:eventsPerVisitWithEvent', 'Events Per Visit With Event');

  addDimension('ga:eventCategory', 'Event Category');

  addDimension('ga:eventAction', 'Event Action');

  addDimension('ga:eventLabel', 'Event Label');

  addDimension('ga:transactionId', 'Transaction ID');

  addDimension('ga:affiliation', 'Affiliation');

  addDimension('ga:visitsToTransaction', 'Visits to Transactions');

  addDimension('ga:daysToTransaction', 'Days to Transaction');

  addDimension('ga:productSku', 'Product Stock Unit');

  addDimension('ga:productName', 'Product Name');

  addDimension('ga:productCategory', 'Product Category');

  addDimension('ga:currencyCode', 'Currency Code');

  addMetric('ga:transactions', 'Transactions');

  addMetric('ga:transactionRevenue', 'Transaction Revenue');

  addMetric('ga:transactionShipping', 'Transaction Shipping Costs');

  addMetric('ga:transactionTax', 'Transaction Tax');

  addMetric('ga:itemQuantity', 'Item Quantity');

  addMetric('ga:uniquePurchases', 'Unique Purchases');

  addMetric('ga:itemRevenue', 'Item Revenue');

  addMetric('ga:localTransactionRevenue', 'Local Transaction Revenue');

  addMetric('ga:localTransactionShipping', 'Local Transaction Shipping Costs');

  addMetric('ga:localTransactionTax', 'Local Transaction Tax');

  addMetric('ga:localItemRevenue', 'Local Item Revenue');

  addMetric('ga:socialInteractions', 'Social Interactions');

  addMetric('ga:uniqueSocialInteractions', 'Unique Social Interactions');

  addMetric('ga:socialInteractionsPerVisit', 'Social Interactions Per Visit');

  addDimension('ga:socialInteractionNetwork', 'Social Interaction Network');

  addDimension('ga:socialInteractionAction', 'Social Interaction Action');

  addDimension('ga:socialInteractionNetworkAction', 'Social Interaction Network Action');

  addDimension('ga:socialInteractionTarget', 'Social Interaction Target');

  addMetric('ga:userTimingValue', 'User Timing Value');

  addMetric('ga:userTimingSample', 'User Timing Sample');

  addMetric('ga:avgUserTimingValue', 'Average User Timing Value');

  addDimension('ga:userTimingCategory', 'User Timing Category');

  addDimension('ga:userTimingLabel', 'User Timing Label');

  addDimension('ga:userTimingVariable', 'User Timing Variable');

  addMetric('ga:exceptions', 'Exceptions');

  addMetric('ga:fatalExceptions', 'Fatal Exceptions');

  addMetric('ga:exceptionDescription', 'Exception Description');

  addMetric('ga:exceptionsPerScreenview', 'Exceptions Per Screenview');

  addMetric('ga:fatalExceptionsPerScreenview', 'Fatal Exceptions Per Screenview');

  addDimension('ga:experimentId', 'Experiment Id');

  addDimension('ga:experimentVariant', 'Experiment Variant');

  addDimension('ga:customVarName(n)', 'Custom Var Name', 'ga:customVarName([0-9]+)');

  addDimension('ga:customVarValue(n)', 'Custom Var Value', 'ga:customVarValue([0-9]+)');

  addDimension('ga:dimension(n)', 'Custom Dimension', 'ga:dimension([0-9]+)');

  addMetric('ga:metric(n)', 'Custom Metric', 'ga:metric([0-9]+)');

  addDimension('ga:date', 'Date');

  addDimension('ga:year', 'Year');

  addDimension('ga:month', 'Month');

  addDimension('ga:week', 'Week');

  addDimension('ga:day', 'Day');

  addDimension('ga:hour', 'Hour');

  addDimension('ga:nthMonth', 'Nth Month');

  addDimension('ga:nthWeek', 'Nth Week');

  addDimension('ga:nthDay', 'Nth Day');

  addDimension('ga:dayOfWeek', 'Day Of Week');

  addDimension('ga:dayOfWeekName', 'Day of Week Name');

  addDimension('ga:dateHour', 'Date Hour');

  addDimension('ga:isoWeek', 'ISO Week');

  addDimension('ga:yearMonth', 'Year Month');

  addDimension('ga:yearWeek', 'Year Week');

  buildRegex();

  exports.metrics = metrics;

  exports.dimensions = dimensions;

  exports.getMetric = getMetric;

  exports.getDimension = getDimension;

  exports.checkMetric = checkMetric;

  exports.checkDimension = checkDimension;

  exports.checkFilter = checkFilter;

  exports.checkSort = checkSort;

  exports.checkSegment = checkSegment;

}).call(this);
